# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYTimesSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

     pod 'Alamofire'
     pod 'AlamofireImage'

  # Pods for NYTimesSwift

  target 'NYTimesSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTimesSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
